"use client";

import React from "react";
import { MicroTask } from "@/utils/dummyTasks";
import MicroTaskCard from "./MicroTaskCard";

interface MicroTaskListProps {
  tasks: MicroTask[];
}

const MicroTaskList: React.FC<MicroTaskListProps> = ({ tasks }) => {
  const highCount = tasks.filter((t) => t.priority === "high").length;
  const totalTime = tasks.reduce((acc, t) => {
    const mins = parseInt(t.estimatedTime);
    return acc + (isNaN(mins) ? 0 : mins);
  }, 0);

  return (
    <section id="micro-task-list" className="w-full mt-12 animate-fade-in">
      {/* Section header */}
      <div className="flex items-center justify-between mb-6">
        <div>
          <h2 className="text-2xl font-bold text-slate-800">
            Generated Micro Tasks
          </h2>
          <p className="text-sm text-slate-500 mt-0.5">
            AI-decomposed steps — click a card to mark it complete
          </p>
        </div>

        {/* Stats pills */}
        <div className="hidden sm:flex items-center gap-2">
          <div className="flex items-center gap-1.5 bg-white/80 border border-slate-200 rounded-full px-3 py-1.5 text-xs font-medium text-slate-600 shadow-sm">
            <span className="w-2 h-2 rounded-full bg-indigo-500" />
            {tasks.length} tasks
          </div>
          <div className="flex items-center gap-1.5 bg-white/80 border border-red-200 rounded-full px-3 py-1.5 text-xs font-medium text-red-600 shadow-sm">
            <span className="w-2 h-2 rounded-full bg-red-500" />
            {highCount} high priority
          </div>
          <div className="flex items-center gap-1.5 bg-white/80 border border-slate-200 rounded-full px-3 py-1.5 text-xs font-medium text-slate-600 shadow-sm">
            <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
            ~{totalTime} min total
          </div>
        </div>
      </div>

      {/* Task cards grid */}
      <div className="grid gap-3">
        {tasks.map((task, index) => (
          <MicroTaskCard key={task.id} task={task} index={index} />
        ))}
      </div>

      {/* Footer note */}
      <p className="text-center text-xs text-slate-400 mt-6 mb-2">
        ✨ Tasks generated by TaskSmith AI — refine your input for more specific results
      </p>
    </section>
  );
};

export default MicroTaskList;
